patrol_node:
  ros__parameters:
    initial_point: [0.0, 0.0, 0.0]
    arrival_tolerance: 0.2
    arrival_min_navigation_time: 5.0
    enforce_goal_orientation: false
    target_points: [
      0.0,0.0,0.0,
      1.0,2.0,3.14,
      -4.5,1.5,1.57,
      -8.0,-5.0,1.57,
      1.0,-5.0,3.14,
      ]
